### ISSUE TITLE
error always happens

### ISSUE THREAD

**Issue by jonasrhee1208** [pmariglia/showdown#101]
the error is 
Traceback (most recent call last):
  File "<string>", line 112, in <module>
  File "C:\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "<string>", line 85, in showdown
  File "C:\Users\IntelNUC-JONAS\ddddddddddd\showdown\teams\load_team.py", line 24, in load_team
    raise ValueError("Path must be file or dir: {}".format(name))
ValueError: Path must be file or dir: gen8/ou/garbage

i tried to fix them but didnt work

**Comment by hypersonicstormm** [comment]
Might be what I encountered in #100. If the sample teams work, the problem you are most likely encountering is what pmariglia said. I'm assuming you're trying to do this on Heroku? From what I understand, when you click on the "Deploy to Heroku" button, it basically creates a clone of the repository. When you go and add something to the original repository, it isn't linked with your Heroku project, so you basically did nothing. You can try the fix I posted in #99. Hope this helps!

**Comment by dittomaster4444** [comment]
I was also having this issue and I'm very much a noob when it comes to this stuff, I didn't realize you have to build the docker image again for it to recognize the teams. it worked perfectly after that

**Comment by pmariglia** [comment]
Closing due to inactivity and inability to reproduce.

If you have more information feel free to re-open.
