### ISSUE TITLE
Error using custom team

### ISSUE THREAD

**Issue by godpow** [pmariglia/showdown#109]
Traceback (most recent call last):
  File "run.py", line 112, in <module>
    asyncio.get_event_loop().run_until_complete(showdown())
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 488, in run_until_complete
    return future.result()
  File "run.py", line 85, in showdown
    team = load_team(config.team_name)
  File "/showdown/teams/load_team.py", line 24, in load_team
    raise ValueError("Path must be file or dir: {}".format(name))
ValueError: Path must be file or dir: gen8/ou/clef_sand2

![image](https://user-images.githubusercontent.com/17231911/164742483-b3b74f9c-bc30-4339-a9f1-6a25068ea611.png)

**Comment by hypersonicstormm** [comment]
I may be wrong, but I'm pretty sure you need to make the team before cloning the project onto whatever you're using to run it. If you make the team after, It won't affect the cloned copy. Hope this helps.

**Comment by pmariglia** [comment]
Are you running in Docker?

If so, the image needs to be re-built every time a new team is added as the code looks within the container for the team.

This shouldn't be necessary - a small change can be made to the run configuration so that the container is able to see the files on your local machine when running as a container.

**Comment by godpow** [comment]
> Are you running in Docker?
> 
> If so, the image needs to be re-built every time a new team is added as the code looks within the container for the team.
> 
> This shouldn't be necessary - a small change can be made to the run configuration so that the container is able to see the files on your local machine when running as a container.

Ye rebuilding it fixed the issue! Thank you! Also question have you thought about adding reinforcement learning in the future?
