### ISSUE TITLE
Problem with nash_equilibrium

### ISSUE THREAD

**Issue by godpow** [pmariglia/showdown#124]
When I use nash_equilibrium I have the gambit directory set and everything but in battles it pops up this error frequently
[Invalid choice] Sorry, too late to make a different move; the next turn has already started
![image](https://user-images.githubusercontent.com/17231911/189477252-c4093412-94e8-4a6e-afe5-74f47cc80667.png)

**Comment by godpow** [comment]
it can also give this other error 
![image](https://user-images.githubusercontent.com/17231911/189477471-17d6e065-c8bb-4666-aa88-2af1585ebc52.png)

**Comment by godpow** [comment]
Output exceeds the [size limit](command:workbench.action.openSettings?%5B%22notebook.output.textLineLimit%22%5D). Open the full output data[ in a text editor](command:workbench.action.openLargeOutput?322d3ec8-7826-49bb-a944-b93db8aabb35)
2022-09-10 03:51:48,313 - ThePowerOfAnime - CRITICAL - Unexpected error message: ['', 'error', "[Invalid choice] There's nothing to choose"]
2022-09-10 03:51:48,313 - ThePowerOfAnime - CRITICAL - Unexpected error message: ['', 'error', "[Invalid choice] There's nothing to choose"]
2022-09-10 03:51:48,316 - ThePowerOfAnime - CRITICAL - Unexpected error message: ['', 'error', "[Invalid choice] There's nothing to choose"]
2022-09-10 03:51:48,316 - ThePowerOfAnime - CRITICAL - Unexpected error message: ['', 'error', "[Invalid choice] There's nothing to choose"]
2022-09-10 03:51:49,514 - ThePowerOfAnime - CRITICAL - Unexpected error message: ['', 'error', "[Invalid choice] Can't move: You need a switch response"]
2022-09-10 03:51:49,514 - ThePowerOfAnime - CRITICAL - Unexpected error message: ['', 'error', "[Invalid choice] Can't move: You need a switch response"]
2022-09-10 03:51:49,515 - ThePowerOfAnime - CRITICAL - Unexpected error message: ['', 'error', "[Invalid choice] Can't move: You need a switch response"]
2022-09-10 03:51:49,515 - ThePowerOfAnime - CRITICAL - Unexpected error message: ['', 'error', "[Invalid choice] Can't move: You need a switch response"]
2022-09-10 03:51:51,971 - ThePowerOfAnime - ERROR - Unhandled exception raised while handling message:
>battle-gen8randombattle-1660659085
|raw|<strong class="message-throttle-notice">Your message was not sent because you've been typing too quickly.</strong>
Traceback (most recent call last):
  File "c:\Users\CyberKira\Documents\test\Pokemon-Showdown-AI-master\AI_MinMax\poke_env\player\player_network_interface.py", line 179, in _handle_message
    await self._handle_battle_message(split_messages)
  File "c:\Users\CyberKira\Documents\test\Pokemon-Showdown-AI-master\AI_MinMax\poke_env\player\player.py", line 322, in _handle_battle_message
    battle._parse_message(split_message)
  File "c:\Users\CyberKira\Documents\test\Pokemon-Showdown-AI-master\AI_MinMax\poke_env\environment\abstract_battle.py", line 691, in _parse_message
    username, rating_info = split_message[2].split("'s rating: ")
ValueError: not enough values to unpack (expected 2, got 1)
2022-09-10 03:51:51,971 - ThePowerOfAnime - ERROR - Unhandled exception raised while handling message:
>battle-gen8randombattle-1660659085
|raw|<strong class="message-throttle-notice">Your message was not sent because you've been typing too quickly.</strong>
Traceback (most recent call last):
  File "c:\Users\CyberKira\Documents\test\Pokemon-Showdown-AI-master\AI_MinMax\poke_env\player\player_network_interface.py", line 179, in _handle_message
    await self._handle_battle_message(split_messages)
...
2022-09-10 03:52:12,943 - ThePowerOfAnime - CRITICAL - Unexpected error message: ['', 'error', "[Invalid choice] Can't move: You need a switch response"]
2022-09-10 03:52:12,943 - ThePowerOfAnime - CRITICAL - Unexpected error message: ['', 'error', "[Invalid choice] Can't move: You need a switch response"]
2022-09-10 03:52:12,944 - ThePowerOfAnime - CRITICAL - Unexpected error message: ['', 'error', "[Invalid choice] Can't move: You need a switch response"]
2022-09-10 03:52:12,944 - ThePowerOfAnime - CRITICAL - Unexpected error message: ['', 'error', "[Invalid choice] Can't move: You need a switch response"]
