### ISSUE TITLE
KeyError: hiddenpower

### ISSUE THREAD

**Issue by louzhang** [pmariglia/showdown#14]
In Gen 4, 5, if a pokemon has a hidden power move, and trys to use it, the ai will crash. It also seems to generate the modified_moves.json (not sure if related).

Here is the stack trace
```Traceback (most recent call last):
  File "./run.py", line 109, in <module>
    asyncio.get_event_loop().run_until_complete(showdown())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "./run.py", line 92, in showdown
    winner = await pokemon_battle(ps_websocket_client, config.pokemon_mode)
  File "/home/snow/Documents/showdown/showdown/run_battle.py", line 174, in pokemon_battle
    best_move = await async_pick_move(battle)
  File "/home/snow/Documents/showdown/showdown/run_battle.py", line 49, in async_pick_move
    pool, find_best_move, battle
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/snow/Documents/showdown/showdown/engine/select_best_move.py", line 210, in find_best_move
    battles = battle.prepare_battles(join_moves_together=True)
  File "/home/snow/Documents/showdown/showdown/battle.py", line 107, in prepare_battles
    pkmn.guess_most_likely_attributes()
  File "/home/snow/Documents/showdown/showdown/battle.py", line 417, in guess_most_likely_attributes
    self.set_likely_moves_unless_revealed()
  File "/home/snow/Documents/showdown/showdown/battle.py", line 391, in set_likely_moves_unless_revealed
    self.moves.append(Move(m))
  File "/home/snow/Documents/showdown/showdown/battle.py", line 529, in __init__
    move_json = all_move_json[name]
KeyError: 'hiddenpowerice6070'

**Comment by pmariglia** [comment]
Hey, thanks for bringing this up!

So this is actually unrelated to the active Pokemon using hiddenpower, but is actually a problem with generations 4/5 trying to use the sets in [data/random_battle_sets.json](https://github.com/pmariglia/showdown/blob/master/data/random_battle_sets.json). The sets assume hiddenpower with base damage of 60, which is incorrect for these generations.

I've gone ahead andmodified this JSON to not mention the base damage of the hiddenpower move. This should make it work across all generations.

Generating `modified_moves.json` is unrelated to what caused the KeyError, but is also just an oversight due to me not testing past generations as much.

As you may have guessed, YMMV with older generations.

Both should be fixed in 8c686f6
