### ISSUE TITLE
Error running with docker

### ISSUE THREAD

**Issue by minax0v** [pmariglia/showdown#156]
Followed all the steps, docker logs output the following error:

``2023-05-07 00:06:17 [ERROR]    Traceback (most recent call last):
2023-05-07 00:06:17   File "run.py", line 103, in <module>
2023-05-07 00:06:17     asyncio.run(showdown())
2023-05-07 00:06:17   File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
2023-05-07 00:06:17     return loop.run_until_complete(main)
2023-05-07 00:06:17   File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
2023-05-07 00:06:17     return future.result()
2023-05-07 00:06:17   File "run.py", line 56, in showdown
2023-05-07 00:06:17     ps_websocket_client = await PSWebsocketClient.create(
2023-05-07 00:06:17   File "/showdown/showdown/websocket_client.py", line 35, in create
2023-05-07 00:06:17     self.websocket = await websockets.connect(self.address)
2023-05-07 00:06:17   File "/usr/local/lib/python3.8/site-packages/websockets/legacy/client.py", line 650, in __await_impl_timeout__
2023-05-07 00:06:17     return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
2023-05-07 00:06:17   File "/usr/local/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
2023-05-07 00:06:17     raise exceptions.TimeoutError()
2023-05-07 00:06:17 asyncio.exceptions.TimeoutError
2023-05-07 00:06:17 
2023-05-07 00:06:17 Traceback (most recent call last):
2023-05-07 00:06:17   File "run.py", line 103, in <module>
2023-05-07 00:06:17     asyncio.run(showdown())
2023-05-07 00:06:17   File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
2023-05-07 00:06:17     return loop.run_until_complete(main)
2023-05-07 00:06:17   File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
2023-05-07 00:06:17     return future.result()
2023-05-07 00:06:17   File "run.py", line 56, in showdown
2023-05-07 00:06:17     ps_websocket_client = await PSWebsocketClient.create(
2023-05-07 00:06:17   File "/showdown/showdown/websocket_client.py", line 35, in create
2023-05-07 00:06:17     self.websocket = await websockets.connect(self.address)
2023-05-07 00:06:17   File "/usr/local/lib/python3.8/site-packages/websockets/legacy/client.py", line 650, in __await_impl_timeout__
2023-05-07 00:06:17     return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
2023-05-07 00:06:17   File "/usr/local/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
2023-05-07 00:06:17     raise exceptions.TimeoutError()
2023-05-07 00:06:17 asyncio.exceptions.TimeoutError

**Comment by pmariglia** [comment]
https://play.pokemonshowdown.com/ seems to be having issues at the moment and I cannot connect either.

**Comment by pmariglia** [comment]
Just tried again and it seems to be fine on my end.

If you still have this issue, could you please share your `env` file (minus the credentials), as well as a more complete stacktrace.

**Comment by minax0v** [comment]
> Just tried again and it seems to be fine on my end.
> 
> If you still have this issue, could you please share your `env` file (minus the credentials), as well as a more complete stacktrace.

Their main server is currently down, really putting the down in Showdown. Oddly enough after I made this issue, running this on Ubuntu works fine, it's just with Windows that's throwing the error.
