### ISSUE TITLE
websockets.exceptions.InvalidMessage: did not receive a valid HTTP response

### ISSUE THREAD

**Issue by zuils** [pmariglia/showdown#185]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/websockets/legacy/client.py", line 135, in read_http_response
    status_code, reason, headers = await read_response(self.reader)
  File "/usr/local/lib/python3.8/site-packages/websockets/legacy/http.py", line 122, in read_response
    raise EOFError("connection closed while reading HTTP status line") from exc
EOFError: connection closed while reading HTTP status line

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run.py", line 103, in <module>
    asyncio.run(showdown())
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "run.py", line 56, in showdown
    ps_websocket_client = await PSWebsocketClient.create(
  File "/showdown/showdown/websocket_client.py", line 35, in create
    self.websocket = await websockets.connect(self.address)
  File "/usr/local/lib/python3.8/site-packages/websockets/legacy/client.py", line 650, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 494, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.8/site-packages/websockets/legacy/client.py", line 658, in __await_impl__
    await protocol.handshake(
  File "/usr/local/lib/python3.8/site-packages/websockets/legacy/client.py", line 322, in handshake
    status_code, response_headers = await self.read_http_response()
  File "/usr/local/lib/python3.8/site-packages/websockets/legacy/client.py", line 141, in read_http_response
    raise InvalidMessage("did not receive a valid HTTP response") from exc
websockets.exceptions.InvalidMessage: did not receive a valid HTTP response

This was using nash_equilibrium and building with docker, never happened to me before

**Comment by pmariglia** [comment]
weird error - does this consistently happen to you, or was it a fluke?

`did not receive a valid HTTP response` does not seem like something that this bot can address

If it keeps happening I'd suggest upgrading to at least python 3.10, and then maybe come back with some more information about what PS server you are connecting to.
