### ISSUE TITLE
Specifying Teams Error

### ISSUE THREAD

**Issue by a18xd** [pmariglia/showdown#202]
I'm trying to get the bot to play on gen9ou but it doesn't recognize the team file, for example I create a team called pro: gen9/ou/pro and an error pops up, I decide to delete that file and take the "example" file where it does work and I delete one team for another and when starting the bot it selects the team that I supposedly deleted which is banned for having spore.

my env is like this:

BATTLE_BOT=safest
WEBSOCKET_URI=wss://sim3.psim.us/showdown/websocket
PS_USERNAME=private
PS_PASSWORD=private
BOT_MODE=SEARCH_LADDER
POKEMON_MODE=gen9ou
RUN_COUNT=1

USER_TO_CHALLENGE=SomeOtherPerson
TEAM_NAME=gen9/ou/pro
SAVE_REPLAY=False

and this would be the pro file:

Dragapult (F) @ Focus Sash  
Ability: Infiltrator  
Tera Type: Water  
EVs: 100 Atk / 156 SpA / 252 Spe  
Hasty Nature  
- Hex  
- Dragon Darts  
- Hydro Pump  
- Will-O-Wisp  

Iron Moth @ Booster Energy  
Ability: Quark Drive  
Tera Type: Grass  
EVs: 120 HP / 4 Def / 132 SpA / 252 Spe  
Timid Nature  
IVs: 0 Atk  
- Fiery Dance  
- Sludge Wave  
- Energy Ball  
- Substitute  

Serperior (F) @ Custap Berry  
Ability: Contrary  
Tera Type: Ground  
EVs: 252 SpA / 4 SpD / 252 Spe  
Timid Nature  
IVs: 0 Atk  
- Leaf Storm  
- Dragon Pulse  
- Tera Blast  
- Endure  

Iron Treads @ Booster Energy  
Ability: Quark Drive  
Tera Type: Ghost  
EVs: 252 Atk / 4 SpD / 252 Spe  
Jolly Nature  
- Stealth Rock  
- Earthquake  
- Ice Spinner  
- Rapid Spin  

Dragonite (F) @ Loaded Dice  
Ability: Multiscale  
Tera Type: Fire  
EVs: 252 Atk / 4 SpD / 252 Spe  
Adamant Nature  
- Dragon Dance  
- Scale Shot  
- Fire Punch  
- Encore  

Greninja (M) @ Life Orb  
Ability: Battle Bond  
Tera Type: Ghost  
EVs: 252 SpA / 4 SpD / 252 Spe  
Timid Nature  
- Surf  
- Dark Pulse  
- Ice Beam  
- Water Shuriken  

answer:

[DEBUG]    Logging in...
[DEBUG]    Received message from websocket: |updateuser| Guest 2515573|0|266|{"blockChallenges":false,"blockPMs":false,"ignoreTickets":false,"hideBattlesFromTrainerCard":false,"blockInvites":false,"doNotDisturb":false,"blockFriendRequests":false,"allowFriendNotifications":false,"displayBattlesToFriends":false,"hideLogins":false,"hiddenNextBattle":false,"inviteOnlyNextBattle":false,"language":null}
|formats|,1|S/V Singles|[Gen 9] Random Battle,f|[Gen 9] Unrated Random Battle,b|[Gen 9] Free-For-All Random Battle,7|[Gen 9] Random Battle (Blitz),f|[Gen 9] Multi Random Battle,5|[Gen 9] OU,e|[Gen 9] Ubers,e|[Gen 9] UU,e|[Gen 9] RU,e|[Gen 9] NU,e|[Gen 9] PU,e|[Gen 9] LC,e|[Gen 9] Monotype,e|[Gen 9] CAP,e|[Gen 9] BSS Reg G,5c|[Gen 9] BSS Reg H,5e|[Gen 9] Custom Game,c|,1|S/V Doubles|[Gen 9] Random Doubles Battle,f|[Gen 9] Doubles OU,e|[Gen 9] Doubles Ubers,e|[Gen 9] Doubles UU,e|[Gen 9] Doubles LC,c|[Gen 9] VGC 2023 Reg D,5c|[Gen 9] VGC 2024 Reg G,5c|[Gen 9] VGC 2024 Reg H,5e|[Gen 9] VGC 2024 Reg H (Bo3),1a|[Gen 9] Doubles Custom Game,c|,1|Unofficial Metagames|[Gen 9] 1v1,e|[Gen 9] 2v2 Doubles,e|[Gen 9] Anything Goes,e|[Gen 9] Ubers UU,e|[Gen 9] ZU,e|[Gen 9] Free-For-All,6|[Gen 9] LC UU,c|[Gen 9] NFE,c|,1|Pet Mods|[Gen 6] Megas Revisited,e|[Gen 1] RBY CAP,e|[Gen 6] NEXT OU,8|,1|Draft|[Gen 9] Draft,8c|[Gen 9] 6v6 Doubles Draft,8c|[Gen 9] 4v4 Doubles Draft,dc|[Gen 9] NatDex Draft,8c|[Gen 9] NatDex 6v6 Doubles Draft,8c|[Gen 9] NatDex LC Draft,8c|[Gen 8] Galar Dex Draft,c|[Gen 8] NatDex Draft,c|[Gen 8] NatDex 4v4 Doubles Draft,1c|[Gen 7] Draft,c|[Gen 6] Draft,c|,2|OM of the Month|[Gen 9] Convergence,e|[Gen 9] Inverse,e|[Gen 9] Inheritance,e|,2|Other Metagames|[Gen 9] Almost Any Ability,e|[Gen 9] Balanced Hackmons,e|[Gen 9] Godly Gift,e|[Gen 9] Mix and Mega,e|[Gen 9] Partners in Crime,e|[Gen 9] Shared Power,e|[Gen 9] STABmons,e|[Gen 7] Pure Hackmons,e|,2|Challengeable OMs|[Gen 9] 350 Cup,c|[Gen 9] Camomons,c|[Gen 9] Category Swap,c|[Gen 9] Cross Evolution,c|[Gen 9] Fervent Impersonation,c|[Gen 9] Foresighters,c|[Gen 9] Fortemons,c|[Gen 9] Frantic Fusions,c|[Gen 9] Full Potential,c|[Gen 9] Pokebilities,c|[Gen 9] Pokemoves,c|[Gen 9] Pure Hackmons,c|[Gen 9] Revelationmons,c|[Gen 9] Sharing is Caring,c|[Gen 9] Tera Donation,c|[Gen 9] The Card Game,c|[Gen 9] The Loser's Game,c|[Gen 9] Trademarked,c|[Gen 9] Triples,c|[Gen 9] Type Split,c|[Gen 6] Pure Hackmons,c|,2|National Dex|[Gen 9] National Dex,e|[Gen 8] National Dex,e|,2|National Dex Other Tiers|[Gen 9] National Dex 35 Pokes,e|[Gen 9] National Dex Ubers,e|[Gen 9] National Dex UU,e|[Gen 9] National Dex RU,c|[Gen 9] National Dex LC,c|[Gen 9] National Dex Monotype,e|[Gen 9] National Dex Doubles,e|[Gen 9] National Dex Doubles Ubers,c|[Gen 9] National Dex Ubers UU,c|[Gen 9] National Dex AG,c|[Gen 9] National Dex BH,c|[Gen 8] National Dex UU,c|[Gen 8] National Dex Monotype,c|,3|Randomized Format Spotlight|[Gen 9] Random Battle (Shared Power, B12P6),f|,3|Randomized Metas|[Gen 9] Random Roulette,d|[Gen 9] Super Staff Bros Ultimate,f|[Gen 9] Monotype Random Battle,f|[Gen 9] Random Battle Mayhem,f|[Gen 9] BSS Factory,1f|[Gen 9] Baby Random Battle,f|[Gen 9] Computer-Generated Teams,f|[Gen 9] Hackmons Cup,f|[Gen 9] Doubles Hackmons Cup,d|[Gen 9] Broken Cup,d|[Gen 9] Challenge Cup 1v1,f|[Gen 9] Challenge Cup 2v2,f|[Gen 9] Challenge Cup 6v6,d|[Gen 9] Metronome Battle,e|[Gen 8] Random Battle,f|[Gen 8] Random Doubles Battle,f|[Gen 8] Free-For-All Random Battle,7|[Gen 8] Multi Random Battle,5|[Gen 8] Battle Factory,f|[Gen 8] BSS Factory,1d|[Gen 8] Hackmons Cup,f|[Gen 8] Metronome Battle,c|[Gen 8] CAP 1v1,d|[Gen 8 BDSP] Random Battle,d|[Gen 7] Random Battle,f|[Gen 7] Battle Factory,f|[Gen 7] BSS Factory,1d|[Gen 7] Hackmons Cup,d|[Gen 7 Let's Go] Random Battle,d|[Gen 6] Random Battle,f|[Gen 6] Battle Factory,9|[Gen 5] Random Battle,f|[Gen 4] Random Battle,f|[Gen 3] Random Battle,f|[Gen 2] Random Battle,f|[Gen 1] Random Battle,f|[Gen 1] Challenge Cup,9|[Gen 1] Hackmons Cup,9|,4|RoA Spotlight|[Gen 3] Ubers,e|[Gen 5] PU,e|[Gen 4] ZU,e|,4|Past Gens OU|[Gen 8] OU,e|[Gen 7] OU,e|[Gen 6] OU,e|[Gen 5] OU,e|[Gen 4] OU,e|[Gen 3] OU,e|[Gen 2] OU,e|[Gen 1] OU,e|,4|Past Gens Doubles OU|[Gen 8] Doubles OU,e|[Gen 7] Doubles OU,e|[Gen 6] Doubles OU,e|[Gen 5] Doubles OU,c|[Gen 4] Doubles OU,c|[Gen 3] Doubles OU,c|,4|Sw/Sh Singles|[Gen 8] Ubers,c|[Gen 8] UU,c|[Gen 8] RU,c|[Gen 8] NU,c|[Gen 8] PU,c|[Gen 8] LC,c|[Gen 8] Monotype,c|[Gen 8] 1v1,c|[Gen 8] Anything Goes,c|[Gen 8] ZU,c|[Gen 8] CAP,c|[Gen 8] Battle Stadium Singles,5c|[Gen 8 BDSP] OU,c|[Gen 8 BDSP] Ubers,c|[Gen 8] Custom Game,c|,4|Sw/Sh Doubles|[Gen 8] Doubles Ubers,c|[Gen 8] Doubles UU,c|[Gen 8] VGC 2022,5c|[Gen 8] VGC 2021,5c|[Gen 8] VGC 2020,5c|[Gen 8 BDSP] Doubles OU,c|[Gen 8 BDSP] Battle Festival Doubles,1c|[Gen 8] Doubles Custom Game,c|,4|US/UM Singles|[Gen 7] Ubers,c|[Gen 7] UU,c|[Gen 7] RU,c|[Gen 7] NU,c|[Gen 7] PU,c|[Gen 7] LC,c|[Gen 7] Monotype,c|[Gen 7] 1v1,c|[Gen 7] Anything Goes,c|[Gen 7] ZU,c|[Gen 7] CAP,c|[Gen 7] Battle Spot Singles,5c|[Gen 7 Let's Go] OU,1c|[Gen 7] Custom Game,c|,4|US/UM Doubles|[Gen 7] Doubles UU,c|[Gen 7] VGC 2019,5c|[Gen 7] VGC 2018,5c|[Gen 7] VGC 2017,5c|[Gen 7] Battle Spot Doubles,5c|[Gen 7 Let's Go] Doubles OU,1c|[Gen 7] Doubles Custom Game,c|,4|OR/AS Singles|[Gen 6] Ubers,c|[Gen 6] UU,c|[Gen 6] RU,c|[Gen 6] NU,c|[Gen 6] PU,c|[Gen 6] LC,c|[Gen 6] Monotype,c|[Gen 6] 1v1,c|[Gen 6] Anything Goes,c|[Gen 6] ZU,c|[Gen 6] CAP,c|[Gen 6] Battle Spot Singles,5c|[Gen 6] Custom Game,c|,4|OR/AS Doubles/Triples|[Gen 6] VGC 2016,5c|[Gen 6] VGC 2015,5c|[Gen 6] VGC 2014,5c|[Gen 6] Battle Spot Doubles,5c|[Gen 6] Doubles Custom Game,c|[Gen 6] Battle Spot Triples,1c|[Gen 6] Triples Custom Game,c|,4|B2/W2 Singles|[Gen 5] Ubers,c|[Gen 5] UU,c|[Gen 5] RU,c|[Gen 5] NU,c|[Gen 5] LC,c|[Gen 5] Monotype,c|[Gen 5] 1v1,c|[Gen 5] ZU,c|[Gen 5] CAP,c|[Gen 5] BW1 OU,c|[Gen 5] GBU Singles,5c|[Gen 5] Custom Game,c|,4|B2/W2 Doubles|[Gen 5] VGC 2013,5c|[Gen 5] VGC 2012,5c|[Gen 5] VGC 2011,5c|[Gen 5] Doubles Custom Game,c|[Gen 5] Triples Custom Game,c|,4|DPP Singles|[Gen 4] Ubers,c|[Gen 4] UU,c|[Gen 4] NU,c|[Gen 4] PU,c|[Gen 4] LC,c|[Gen 4] Anything Goes,c|[Gen 4] 1v1,c|[Gen 4] CAP,c|[Gen 4] Custom Game,c|,4|DPP Doubles|[Gen 4] VGC 2010,1c|[Gen 4] VGC 2009,1c|[Gen 4] Doubles Custom Game,c|,4|Past Generations|[Gen 3] UU,c|[Gen 3] RU,c|[Gen 3] NU,c|[Gen 3] PU,c|[Gen 3] LC,c|[Gen 3] 1v1,c|[Gen 3] ZU,e|[Gen 3] Custom Game,c|[Gen 3] Doubles Custom Game,c|[Gen 2] Ubers,c|[Gen 2] UU,c|[Gen 2] NU,c|[Gen 2] PU,c|[Gen 2] 1v1,c|[Gen 2] ZU,c|[Gen 2] NC 2000,c|[Gen 2] Stadium OU,c|[Gen 2] Custom Game,c|[Gen 1] Ubers,c|[Gen 1] UU,c|[Gen 1] NU,c|[Gen 1] PU,c|[Gen 1] 1v1,c|[Gen 1] ZU,c|[Gen 1] Japanese OU,c|[Gen 1] Stadium OU,c|[Gen 1] Tradebacks OU,c|[Gen 1] NC 1997,c|[Gen 1] Custom Game,c
[DEBUG]    Received message from websocket: |challstr|4|aceb507469fd646306558e12ba07b267fdbabab9c66d080f54628fc125e88e027ee57ddfc115ceaa8b749a4f82d97894fc586b8f283f581cc2772da56925f15c66b6139de858bbeed4a329afcbcb90a58f72c83fa994066d2fcbfbd8fb5fbb3c4d92240dbc0aae906c477cfdc8b9424577a7707305acee8c7b554ed6e2248523
[DEBUG]    Successfully logged in
[DEBUG]    Sending message to websocket: |/trn pkdf_ia,0,aceb507469fd646306558e12ba07b267fdbabab9c66d080f54628fc125e88e027ee57ddfc115ceaa8b749a4f82d97894fc586b8f283f581cc2772da56925f15c66b6139de858bbeed4a329afcbcb90a58f72c83fa994066d2fcbfbd8fb5fbb3c4d92240dbc0aae906c477cfdc8b9424577a7707305acee8c7b554ed6e2248523,pkdfia,4,1728099968,sim3.psim.us,7a3b71ed9e34cecd1728099968,9bf07728b47dc51f,;c0d342d4a366767b24c659c12821651730eafe1bf4eb6ac32589a94383c2ed6d230a792fe8039c3aecfa05d265f69c1d4115975557b2ca783740fa21948e4a1410a9f5896c89d4bafb1844cf1e9aa90f2ae7a67202100979560c8d439dcf73f34c7da960adeffbbc9099d2f122f262c44a15aa6300562828c316745ad9b98cc57b7888789f1617afd31c8f9a12410f49be1877c1e127187b57c8b33b91bd79d3592251c5da44b3143bd7564487c745a173bcec6720365534eec3f0a7008d0904effe0c39d4a349939214546514a03c07898b5a75871137f99b1978f2a8a8e61e5f677f852302e5b52a5daf145d8eb7d6379b28e1591675e30d83b7a511745daad8df40b0a8996a0a98fcaf0968945943f5c903fc1595f9053dee31c1f9038ec0a759de8f7be3591233fb2501567aa066fdee14af74dc7b75fd9fe451ba7e797c38022ad241907fb2aff2118d41143c86de0fc56be3f42ab36f5f2b4b7b0de5cf330291253cb692d9676e4cbae71eba21a3f0f5f8b48b202604bff8c4f485356bfe3382525df472db96875a29543d63652945e19609de665ba0fb0cf61790e3ae44784c9b8007b23dd547585d594333b77a64293acb6394f624a8f9aac8f3c37153a034bbc642034dbda04788692dfd663bb0491cba780b196b1cbbf727e16d46246be77591ad8ad69b5554ef18024093116c6a8bad66af7fa02acdeaaab046c9
[ERROR]    Traceback (most recent call last):
  File "run.py", line 103, in <module>
    asyncio.run(showdown())
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "run.py", line 69, in showdown
    team = load_team(ShowdownConfig.team)
  File "/showdown/teams/load_team.py", line 24, in load_team
    raise ValueError("Path must be file or dir: {}".format(name))
ValueError: Path must be file or dir: gen9/ou/pro

Traceback (most recent call last):
  File "run.py", line 103, in <module>
    asyncio.run(showdown())
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "run.py", line 69, in showdown
    team = load_team(ShowdownConfig.team)
  File "/showdown/teams/load_team.py", line 24, in load_team
    raise ValueError("Path must be file or dir: {}".format(name))
ValueError: Path must be file or dir: gen9/ou/pro

And I'm telling you, even if I take the file called "example" and change the team, it still recognizes the ting-lu team, etc... when starting the command

By the way, just in case, it works, I've tried it in random battle

I just want to be able to set up the team I want to play Anything Goes against a friend, but I would like it to work flawlessly.

Thank you so much.

**Comment by a18xd** [comment]
Fixed: you have to docker build . -t showdown every time you edit something in the directory! Thanks
