### ISSUE TITLE
Ditto is breaking the bot when it transforms

### ISSUE THREAD

**Issue by HarounAns** [pmariglia/showdown#29]
My bot breaks anytime the user transforms with ditto:
```
[battle_modifier]        [DEBUG]    Opponent has switched - clearing the last used move
[battle_modifier]        [DEBUG]    Opponent ditto transformed into dracozolt
Traceback (most recent call last):
  File "run.py", line 115, in <module>
    asyncio.get_event_loop().run_until_complete(showdown())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "run.py", line 96, in showdown
    winner = await pokemon_battle(ps_websocket_client, config.pokemon_mode)
  File "/showdown/showdown/run_battle.py", line 170, in pokemon_battle
    action_required = await async_update_battle(battle, msg)
  File "/showdown/showdown/battle_modifier.py", line 772, in async_update_battle
    return update_battle(battle, msg)
  File "/showdown/showdown/battle_modifier.py", line 753, in update_battle
    function_to_call(battle, split_msg)
  File "/showdown/showdown/battle_modifier.py", line 557, in transform
    battle.opponent.active.stats = deepcopy(transformed_into.stats)
AttributeError: 'NoneType' object has no attribute 'stats'
```

![image](https://user-images.githubusercontent.com/20847319/74613806-c0280a00-50df-11ea-924b-1239f930844c.png)

I'm not sure if this is replicatable. I did make some changes on my fork but I'm not sure if they're causing this. It may be the nicknames that break it. Theres a line of code that says:

```
if battle_copy.user.active.name == transformed_into_name or battle_copy.user.active.name.startswith(transformed_into_name):
            transformed_into = battle_copy.user.active
```

It might be the nicknames that is messing up the bot.

**Comment by pmariglia** [comment]
This is happening on your fork?

I can see your fork is 77 commits behind so you may be experiencing an issue that has already been resolved.

Try to update with the master branch and let me know if you still experience this issue.

**Comment by pmariglia** [comment]
Going to close this as it has been over a month.

Please feel free to re-open if you can provide some more details.
