### ISSUE TITLE
Error when starting battle

### ISSUE THREAD

**Issue by LINKdiscordd** [pmariglia/showdown#44]
Traceback (most recent call last):

File "run.py", line 110, in <module>

asyncio.get_event_loop().run_until_complete(showdown())

File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete

return future.result()

File "run.py", line 93, in showdown

winner = await pokemon_battle(ps_websocket_client, config.pokemon_mode)

File "/showdown/showdown/run_battle.py", line 156, in pokemon_battle

battle = await start_battle(ps_websocket_client, pokemon_battle_type)

File "/showdown/showdown/run_battle.py", line 147, in start_battle

battle = await start_standard_battle(ps_websocket_client, pokemon_battle_type)

File "/showdown/showdown/run_battle.py", line 137, in start_standard_battle

await handle_team_preview(battle, ps_websocket_client)

File "/showdown/showdown/run_battle.py", line 47, in handle_team_preview

best_move = await async_pick_move(battle_copy)

File "/showdown/showdown/run_battle.py", line 32, in async_pick_move

pool, battle_copy.find_best_move

File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run

result = self.fn(*self.args, **self.kwargs)

File "/showdown/showdown/battle_bots/nash_equilibrium/main.py", line 188, in find_best_move

scores = get_payoff_matrix(mutator, user_options, opponent_options, prune=False)

File "/showdown/showdown/engine/select_best_move.py", line 115, in get_payoff_matrix

safest = pick_safest(get_payoff_matrix(mutator, next_turn_user_options, next_turn_opponent_options, depth=depth, prune=prune))

File "/showdown/showdown/engine/select_best_move.py", line 102, in get_payoff_matrix

state_instructions = get_all_state_instructions(mutator, user_move, opponent_move)

File "/showdown/showdown/engine/find_state_instructions.py", line 456, in get_all_state_instructions

instructions = get_state_instructions_from_move(mutator, opponent_move, user_move, constants.OPPONENT, constants.SELF, True, instructions)

File "/showdown/showdown/engine/find_state_instructions.py", line 379, in get_state_instructions_from_move

temp_instructions += instruction_generator.get_states_from_boosts(mutator, boosts_target, boosts, boosts_chance, instruction_set)

File "/showdown/showdown/engine/instruction_generator.py", line 756, in get_states_from_boosts

new_boost = pkmn_boost + v

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

**Comment by pmariglia** [comment]
Hey, thanks for opening this issue.

Looks like I made an error when adding the JSON for the new moves - you must've been using a zapdosgalar with thunderouskick. Should be fixed in 2230dc09f7ecef45770173c13e4d00066eec95a8.

**Comment by pmariglia** [comment]
This is fixed - closing
