### ISSUE TITLE
can't add new team I get the following error:

### ISSUE THREAD

**Issue by timothychen04** [pmariglia/showdown#64]
Traceback (most recent call last):
  File "run.py", line 111, in <module>
    asyncio.get_event_loop().run_until_complete(showdown())
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 488, in run_until_complete
    return future.result()
  File "run.py", line 84, in showdown
    team = load_team(config.team_name)
  File "/showdown/teams/load_team.py", line 24, in load_team
    raise ValueError("Path must be file or dir: {}".format(name))
ValueError: Path must be file or dir: gen8/ou2
 
And when I tried replacing your sample team with my own team it went back to the sample team
Do teams need to be defined elsewhere other than teams/teams/gen8/ou

**Comment by timothychen04** [comment]
never I fixed it, I just had to rebuild the docker image
