### ISSUE TITLE
crashing when deploying to heroku

### ISSUE THREAD

**Issue by 0x0403** [pmariglia/showdown#69]
2021-07-07T05:18:34.457435+00:00 app[worker.1]: Traceback (most recent call last):
2021-07-07T05:18:34.457493+00:00 app[worker.1]:   File "run.py", line 111, in <module>
2021-07-07T05:18:34.457913+00:00 app[worker.1]:     asyncio.get_event_loop().run_until_complete(showdown())
2021-07-07T05:18:34.457947+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/asyncio/base_events.py", line 488, in run_until_complete
2021-07-07T05:18:34.458482+00:00 app[worker.1]:     return future.result()
2021-07-07T05:18:34.458519+00:00 app[worker.1]:   File "run.py", line 94, in showdown
2021-07-07T05:18:34.458839+00:00 app[worker.1]:     winner = await pokemon_battle(ps_websocket_client, config.pokemon_mode)
2021-07-07T05:18:34.459865+00:00 app[worker.1]:   File "/app/showdown/run_battle.py", line 175, in pokemon_battle
2021-07-07T05:18:34.460167+00:00 app[worker.1]:     battle = await start_battle(ps_websocket_client, pokemon_battle_type)
2021-07-07T05:18:34.460202+00:00 app[worker.1]:   File "/app/showdown/run_battle.py", line 164, in start_battle
2021-07-07T05:18:34.460518+00:00 app[worker.1]:     battle = await start_random_battle(ps_websocket_client, pokemon_battle_type)
2021-07-07T05:18:34.460553+00:00 app[worker.1]:   File "/app/showdown/run_battle.py", line 120, in start_random_battle
2021-07-07T05:18:34.460795+00:00 app[worker.1]:     await read_messages_until_first_pokemon_is_seen(ps_websocket_client, battle, opponent_id, user_json)
2021-07-07T05:18:34.460831+00:00 app[worker.1]:   File "/app/showdown/run_battle.py", line 109, in read_messages_until_first_pokemon_is_seen
2021-07-07T05:18:34.461065+00:00 app[worker.1]:     best_move = await async_pick_move(battle)
2021-07-07T05:18:34.461098+00:00 app[worker.1]:   File "/app/showdown/run_battle.py", line 34, in async_pick_move
2021-07-07T05:18:34.461286+00:00 app[worker.1]:     pool, battle_copy.find_best_move
2021-07-07T05:18:34.461322+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/concurrent/futures/thread.py", line 56, in run
2021-07-07T05:18:34.461530+00:00 app[worker.1]:     result = self.fn(*self.args, **self.kwargs)
2021-07-07T05:18:34.461567+00:00 app[worker.1]:   File "/app/showdown/battle_bots/nash_equilibrium/main.py", line 191, in find_best_move
2021-07-07T05:18:34.461943+00:00 app[worker.1]:     decision = pick_move_in_equilibrium_from_multiple_score_lookups(list_of_payoffs)
2021-07-07T05:18:34.461980+00:00 app[worker.1]:   File "/app/showdown/battle_bots/nash_equilibrium/main.py", line 154, in pick_move_in_equilibrium_from_multiple_score_lookups
2021-07-07T05:18:34.463665+00:00 app[worker.1]:     weighted_choices = get_weighted_choices_from_multiple_score_lookups(score_lookups)
2021-07-07T05:18:34.463704+00:00 app[worker.1]:   File "/app/showdown/battle_bots/nash_equilibrium/main.py", line 139, in get_weighted_choices_from_multiple_score_lookups
2021-07-07T05:18:34.464035+00:00 app[worker.1]:     eq = find_nash_equilibrium(sl)
2021-07-07T05:18:34.464073+00:00 app[worker.1]:   File "/app/showdown/battle_bots/nash_equilibrium/main.py", line 112, in find_nash_equilibrium
2021-07-07T05:18:34.464303+00:00 app[worker.1]:     equilibria = find_all_equilibria(df)
2021-07-07T05:18:34.464340+00:00 app[worker.1]:   File "/app/showdown/battle_bots/nash_equilibrium/main.py", line 88, in find_all_equilibria
2021-07-07T05:18:34.464568+00:00 app[worker.1]:     sp = subprocess.Popen(cmd, stdout=subprocess.PIPE, stdin=subprocess.PIPE)
2021-07-07T05:18:34.464591+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/subprocess.py", line 729, in __init__
2021-07-07T05:18:34.465192+00:00 app[worker.1]:     restore_signals, start_new_session)
2021-07-07T05:18:34.465197+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/subprocess.py", line 1364, in _execute_child
2021-07-07T05:18:34.466254+00:00 app[worker.1]:     raise child_exception_type(errno_num, err_msg, err_filename)
2021-07-07T05:18:34.466318+00:00 app[worker.1]: PermissionError: [Errno 13] Permission denied: ''
2021-07-07T05:18:34.722412+00:00 heroku[worker.1]: Process exited with status 1
2021-07-07T05:18:34.889947+00:00 heroku[worker.1]: State changed from up to crashed

**Comment by 0x0403** [comment]
pretty sure its just an issue when using nash_equilibrium

**Comment by pmariglia** [comment]
> pretty sure its just an issue when using nash_equilibrium

It is. Using that decision making method relies on some binaries from the [Gambit project](http://www.gambit-project.org/). These are pre-compiled in the Docker image of this repository.

From the README of this repo:
```
The Nash Equilibrium is calculated using command-line tools provided by the Gambit project. This decision method should only be used when running with Docker and will fail otherwise.
```

**Comment by 0x0403** [comment]
> > pretty sure its just an issue when using nash_equilibrium
> 
> It is. Using that decision making method relies on some binaries from the [Gambit project](http://www.gambit-project.org/). These binaries are included in the Docker image of this repository.
> 
> From the README of this repo:
> 
> ```
> The Nash Equilibrium is calculated using command-line tools provided by the Gambit project. This decision method should only be used when running with Docker and will fail otherwise.
> ```

thank you
